# Generated by Django 4.1.5 on 2023-01-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pockets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocket',
            name='items',
            field=models.ManyToManyField(related_name='pockets', to='pockets.pocket'),
        ),
    ]
