# Generated by Django 4.1.5 on 2023-01-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pockets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocket',
            name='multiplier',
            field=models.IntegerField(default=1),
        ),
    ]
