# Generated by Django 4.1.5 on 2023-01-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('pockets', '0002_pocket_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocket',
            name='items',
            field=models.ManyToManyField(related_name='pockets', to='items.item'),
        ),
    ]
