# Generated by Django 4.1.5 on 2023-01-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='items',
            field=models.ManyToManyField(default=4, related_name='items', to='items.item'),
        ),
    ]
