# Generated by Django 4.1.5 on 2023-01-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_multiplier'),
        ('jwt_auth', '0002_alter_user_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='items',
            field=models.ManyToManyField(default=[4], related_name='users', to='items.item'),
        ),
    ]
