# Generated by Django 4.1.5 on 2023-01-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('item_image', models.CharField(max_length=300)),
                ('red_packets_needed_to_unlock', models.IntegerField(default=1)),
                ('multiplier', models.IntegerField(default=1)),
            ],
        ),
    ]
