# Generated by Django 4.1.5 on 2023-01-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='multiplier',
            field=models.IntegerField(default=1),
        ),
    ]
